// Generated by gencpp from file robot_pkg/xy.msg
// DO NOT EDIT!


#ifndef ROBOT_PKG_MESSAGE_XY_H
#define ROBOT_PKG_MESSAGE_XY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_pkg
{
template <class ContainerAllocator>
struct xy_
{
  typedef xy_<ContainerAllocator> Type;

  xy_()
    : header()
    , x(0.0)
    , y(0.0)
    , angle(0.0)
    , mode(0)  {
    }
  xy_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , angle(0.0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _angle_type;
  _angle_type angle;

   typedef int8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::robot_pkg::xy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_pkg::xy_<ContainerAllocator> const> ConstPtr;

}; // struct xy_

typedef ::robot_pkg::xy_<std::allocator<void> > xy;

typedef boost::shared_ptr< ::robot_pkg::xy > xyPtr;
typedef boost::shared_ptr< ::robot_pkg::xy const> xyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_pkg::xy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_pkg::xy_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_pkg::xy_<ContainerAllocator1> & lhs, const ::robot_pkg::xy_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.angle == rhs.angle &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_pkg::xy_<ContainerAllocator1> & lhs, const ::robot_pkg::xy_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_pkg::xy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_pkg::xy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_pkg::xy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_pkg::xy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_pkg::xy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_pkg::xy_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_pkg::xy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecbc2edcd0a096d8c29d6fe677deeb7c";
  }

  static const char* value(const ::robot_pkg::xy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xecbc2edcd0a096d8ULL;
  static const uint64_t static_value2 = 0xc29d6fe677deeb7cULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_pkg::xy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_pkg/xy";
  }

  static const char* value(const ::robot_pkg::xy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_pkg::xy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 x\n"
"float64 y\n"
"float64 angle\n"
"int8 mode\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_pkg::xy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_pkg::xy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angle);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_pkg::xy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_pkg::xy_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PKG_MESSAGE_XY_H
